package com.jzt.api.dao;

import com.jzt.api.domain.AppUserFavorite;
import com.jzt.api.domain.AppUserFavoriteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppUserFavoriteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_favorite
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int countByExample(AppUserFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_favorite
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int deleteByExample(AppUserFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_favorite
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_favorite
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int insert(AppUserFavorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_favorite
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int insertSelective(AppUserFavorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_favorite
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    List<AppUserFavorite> selectByExample(AppUserFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_favorite
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    AppUserFavorite selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_favorite
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByExampleSelective(@Param("record") AppUserFavorite record, @Param("example") AppUserFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_favorite
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByExample(@Param("record") AppUserFavorite record, @Param("example") AppUserFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_favorite
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByPrimaryKeySelective(AppUserFavorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user_favorite
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByPrimaryKey(AppUserFavorite record);
}