package com.jzt.api.dao;

import com.jzt.api.domain.BankInfo;
import com.jzt.api.domain.BankInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BankInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_info
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int countByExample(BankInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_info
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int deleteByExample(BankInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_info
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_info
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int insert(BankInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_info
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int insertSelective(BankInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_info
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    List<BankInfo> selectByExample(BankInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_info
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    BankInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_info
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByExampleSelective(@Param("record") BankInfo record, @Param("example") BankInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_info
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByExample(@Param("record") BankInfo record, @Param("example") BankInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_info
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByPrimaryKeySelective(BankInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_info
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByPrimaryKey(BankInfo record);
}