package com.jzt.api.dao;

import com.jzt.api.domain.CompanyStructure;
import com.jzt.api.domain.CompanyStructureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompanyStructureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_structure
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int countByExample(CompanyStructureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_structure
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int deleteByExample(CompanyStructureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_structure
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_structure
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int insert(CompanyStructure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_structure
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int insertSelective(CompanyStructure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_structure
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    List<CompanyStructure> selectByExampleWithBLOBs(CompanyStructureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_structure
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    List<CompanyStructure> selectByExample(CompanyStructureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_structure
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    CompanyStructure selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_structure
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByExampleSelective(@Param("record") CompanyStructure record, @Param("example") CompanyStructureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_structure
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") CompanyStructure record, @Param("example") CompanyStructureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_structure
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByExample(@Param("record") CompanyStructure record, @Param("example") CompanyStructureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_structure
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByPrimaryKeySelective(CompanyStructure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_structure
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(CompanyStructure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_structure
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByPrimaryKey(CompanyStructure record);
}