package com.jzt.api.dao;

import com.jzt.api.domain.Exposure;
import com.jzt.api.domain.ExposureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExposureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exposure
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int countByExample(ExposureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exposure
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int deleteByExample(ExposureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exposure
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int deleteByPrimaryKey(Integer eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exposure
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int insert(Exposure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exposure
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int insertSelective(Exposure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exposure
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    List<Exposure> selectByExampleWithBLOBs(ExposureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exposure
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    List<Exposure> selectByExample(ExposureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exposure
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    Exposure selectByPrimaryKey(Integer eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exposure
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByExampleSelective(@Param("record") Exposure record, @Param("example") ExposureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exposure
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") Exposure record, @Param("example") ExposureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exposure
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByExample(@Param("record") Exposure record, @Param("example") ExposureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exposure
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByPrimaryKeySelective(Exposure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exposure
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Exposure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exposure
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByPrimaryKey(Exposure record);
}