package com.jzt.api.dao;

import com.jzt.api.domain.P2pPlat;
import com.jzt.api.domain.P2pPlatExample;
import com.jzt.api.domain.P2pPlatWithBLOBs;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface P2pPlatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p2p_plat
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int countByExample(P2pPlatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p2p_plat
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int deleteByExample(P2pPlatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p2p_plat
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p2p_plat
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int insert(P2pPlatWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p2p_plat
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int insertSelective(P2pPlatWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p2p_plat
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    List<P2pPlatWithBLOBs> selectByExampleWithBLOBs(P2pPlatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p2p_plat
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    List<P2pPlat> selectByExample(P2pPlatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p2p_plat
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    P2pPlatWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p2p_plat
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByExampleSelective(@Param("record") P2pPlatWithBLOBs record, @Param("example") P2pPlatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p2p_plat
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") P2pPlatWithBLOBs record, @Param("example") P2pPlatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p2p_plat
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByExample(@Param("record") P2pPlat record, @Param("example") P2pPlatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p2p_plat
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByPrimaryKeySelective(P2pPlatWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p2p_plat
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(P2pPlatWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p2p_plat
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByPrimaryKey(P2pPlat record);

    int removeByPrimaryKey(P2pPlat record);

    /**
     *
     * @param startRow,pageSize
     * @return 返回包含基本信息的p2p平台列表
     */

    List<Map> listP2pPlatWithPlatform(@Param("startRow") int startRow, @Param("pageSize") int pageSize);
}