package com.jzt.api.dao;

import com.jzt.api.domain.PartnerRelCompany;
import com.jzt.api.domain.PartnerRelCompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PartnerRelCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_rel_company
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int countByExample(PartnerRelCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_rel_company
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int deleteByExample(PartnerRelCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_rel_company
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_rel_company
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int insert(PartnerRelCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_rel_company
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int insertSelective(PartnerRelCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_rel_company
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    List<PartnerRelCompany> selectByExample(PartnerRelCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_rel_company
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    PartnerRelCompany selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_rel_company
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByExampleSelective(@Param("record") PartnerRelCompany record, @Param("example") PartnerRelCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_rel_company
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByExample(@Param("record") PartnerRelCompany record, @Param("example") PartnerRelCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_rel_company
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByPrimaryKeySelective(PartnerRelCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_rel_company
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByPrimaryKey(PartnerRelCompany record);
}