package com.jzt.api.dao;

import com.jzt.api.domain.SensitiveWord;
import com.jzt.api.domain.SensitiveWordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SensitiveWordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int countByExample(SensitiveWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int deleteByExample(SensitiveWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int insert(SensitiveWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int insertSelective(SensitiveWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    List<SensitiveWord> selectByExample(SensitiveWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    SensitiveWord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByExampleSelective(@Param("record") SensitiveWord record, @Param("example") SensitiveWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByExample(@Param("record") SensitiveWord record, @Param("example") SensitiveWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByPrimaryKeySelective(SensitiveWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    int updateByPrimaryKey(SensitiveWord record);
}