package com.jzt.api.domain;

import java.util.Date;

public class AdverProductNow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adver_product_now.id
     *
     * @mbggenerated Sun Mar 12 23:14:31 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adver_product_now.feature
     *
     * @mbggenerated Sun Mar 12 23:14:31 CST 2017
     */
    private String feature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adver_product_now.related_admin
     *
     * @mbggenerated Sun Mar 12 23:14:31 CST 2017
     */
    private Integer relatedAdmin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adver_product_now.sort_value
     *
     * @mbggenerated Sun Mar 12 23:14:31 CST 2017
     */
    private Float sortValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adver_product_now.product_id
     *
     * @mbggenerated Sun Mar 12 23:14:31 CST 2017
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adver_product_now.publish_time
     *
     * @mbggenerated Sun Mar 12 23:14:31 CST 2017
     */
    private Date publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adver_product_now.idx
     *
     * @mbggenerated Sun Mar 12 23:14:31 CST 2017
     */
    private Integer idx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adver_product_now.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:31 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adver_product_now.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:31 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adver_product_now.id
     *
     * @return the value of adver_product_now.id
     *
     * @mbggenerated Sun Mar 12 23:14:31 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adver_product_now.id
     *
     * @param id the value for adver_product_now.id
     *
     * @mbggenerated Sun Mar 12 23:14:31 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adver_product_now.feature
     *
     * @return the value of adver_product_now.feature
     *
     * @mbggenerated Sun Mar 12 23:14:31 CST 2017
     */
    public String getFeature() {
        return feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adver_product_now.feature
     *
     * @param feature the value for adver_product_now.feature
     *
     * @mbggenerated Sun Mar 12 23:14:31 CST 2017
     */
    public void setFeature(String feature) {
        this.feature = feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adver_product_now.related_admin
     *
     * @return the value of adver_product_now.related_admin
     *
     * @mbggenerated Sun Mar 12 23:14:31 CST 2017
     */
    public Integer getRelatedAdmin() {
        return relatedAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adver_product_now.related_admin
     *
     * @param relatedAdmin the value for adver_product_now.related_admin
     *
     * @mbggenerated Sun Mar 12 23:14:31 CST 2017
     */
    public void setRelatedAdmin(Integer relatedAdmin) {
        this.relatedAdmin = relatedAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adver_product_now.sort_value
     *
     * @return the value of adver_product_now.sort_value
     *
     * @mbggenerated Sun Mar 12 23:14:31 CST 2017
     */
    public Float getSortValue() {
        return sortValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adver_product_now.sort_value
     *
     * @param sortValue the value for adver_product_now.sort_value
     *
     * @mbggenerated Sun Mar 12 23:14:31 CST 2017
     */
    public void setSortValue(Float sortValue) {
        this.sortValue = sortValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adver_product_now.product_id
     *
     * @return the value of adver_product_now.product_id
     *
     * @mbggenerated Sun Mar 12 23:14:31 CST 2017
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adver_product_now.product_id
     *
     * @param productId the value for adver_product_now.product_id
     *
     * @mbggenerated Sun Mar 12 23:14:31 CST 2017
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adver_product_now.publish_time
     *
     * @return the value of adver_product_now.publish_time
     *
     * @mbggenerated Sun Mar 12 23:14:31 CST 2017
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adver_product_now.publish_time
     *
     * @param publishTime the value for adver_product_now.publish_time
     *
     * @mbggenerated Sun Mar 12 23:14:31 CST 2017
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adver_product_now.idx
     *
     * @return the value of adver_product_now.idx
     *
     * @mbggenerated Sun Mar 12 23:14:31 CST 2017
     */
    public Integer getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adver_product_now.idx
     *
     * @param idx the value for adver_product_now.idx
     *
     * @mbggenerated Sun Mar 12 23:14:31 CST 2017
     */
    public void setIdx(Integer idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adver_product_now.create_time
     *
     * @return the value of adver_product_now.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:31 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adver_product_now.create_time
     *
     * @param createTime the value for adver_product_now.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:31 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adver_product_now.update_time
     *
     * @return the value of adver_product_now.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:31 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adver_product_now.update_time
     *
     * @param updateTime the value for adver_product_now.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:31 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}