package com.jzt.api.domain;

import java.util.Date;

public class BankEval {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_eval.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_eval.plat_id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer platId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_eval.release_score
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Double releaseScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_eval.profit_score
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Double profitScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_eval.risk_score
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Double riskScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_eval.product_rich_score
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Double productRichScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_eval.info_disclosure_score
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Double infoDisclosureScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_eval.evaluate_score
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Double evaluateScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_eval.total_score
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Double totalScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_eval.is_delete
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_eval.start_date
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_eval.end_date
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_eval.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_eval.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_eval.id
     *
     * @return the value of bank_eval.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_eval.id
     *
     * @param id the value for bank_eval.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_eval.plat_id
     *
     * @return the value of bank_eval.plat_id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getPlatId() {
        return platId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_eval.plat_id
     *
     * @param platId the value for bank_eval.plat_id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setPlatId(Integer platId) {
        this.platId = platId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_eval.release_score
     *
     * @return the value of bank_eval.release_score
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Double getReleaseScore() {
        return releaseScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_eval.release_score
     *
     * @param releaseScore the value for bank_eval.release_score
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setReleaseScore(Double releaseScore) {
        this.releaseScore = releaseScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_eval.profit_score
     *
     * @return the value of bank_eval.profit_score
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Double getProfitScore() {
        return profitScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_eval.profit_score
     *
     * @param profitScore the value for bank_eval.profit_score
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setProfitScore(Double profitScore) {
        this.profitScore = profitScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_eval.risk_score
     *
     * @return the value of bank_eval.risk_score
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Double getRiskScore() {
        return riskScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_eval.risk_score
     *
     * @param riskScore the value for bank_eval.risk_score
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setRiskScore(Double riskScore) {
        this.riskScore = riskScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_eval.product_rich_score
     *
     * @return the value of bank_eval.product_rich_score
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Double getProductRichScore() {
        return productRichScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_eval.product_rich_score
     *
     * @param productRichScore the value for bank_eval.product_rich_score
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setProductRichScore(Double productRichScore) {
        this.productRichScore = productRichScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_eval.info_disclosure_score
     *
     * @return the value of bank_eval.info_disclosure_score
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Double getInfoDisclosureScore() {
        return infoDisclosureScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_eval.info_disclosure_score
     *
     * @param infoDisclosureScore the value for bank_eval.info_disclosure_score
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setInfoDisclosureScore(Double infoDisclosureScore) {
        this.infoDisclosureScore = infoDisclosureScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_eval.evaluate_score
     *
     * @return the value of bank_eval.evaluate_score
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Double getEvaluateScore() {
        return evaluateScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_eval.evaluate_score
     *
     * @param evaluateScore the value for bank_eval.evaluate_score
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setEvaluateScore(Double evaluateScore) {
        this.evaluateScore = evaluateScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_eval.total_score
     *
     * @return the value of bank_eval.total_score
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Double getTotalScore() {
        return totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_eval.total_score
     *
     * @param totalScore the value for bank_eval.total_score
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setTotalScore(Double totalScore) {
        this.totalScore = totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_eval.is_delete
     *
     * @return the value of bank_eval.is_delete
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_eval.is_delete
     *
     * @param isDelete the value for bank_eval.is_delete
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_eval.start_date
     *
     * @return the value of bank_eval.start_date
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_eval.start_date
     *
     * @param startDate the value for bank_eval.start_date
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_eval.end_date
     *
     * @return the value of bank_eval.end_date
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_eval.end_date
     *
     * @param endDate the value for bank_eval.end_date
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_eval.create_time
     *
     * @return the value of bank_eval.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_eval.create_time
     *
     * @param createTime the value for bank_eval.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_eval.update_time
     *
     * @return the value of bank_eval.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_eval.update_time
     *
     * @param updateTime the value for bank_eval.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}