package com.jzt.api.domain;

import java.util.Date;

public class Businessman {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businessman.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businessman.cid
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businessman.name
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businessman.img_dir
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String imgDir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businessman.img
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businessman.post
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String post;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businessman.sex
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businessman.age
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businessman.education
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businessman.school_type
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer schoolType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businessman.school
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String school;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businessman.school_type2
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer schoolType2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businessman.school2
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String school2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businessman.has_professional_certificate
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer hasProfessionalCertificate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businessman.professional_certificate
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String professionalCertificate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businessman.work_experience
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer workExperience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businessman.enterprise_type
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer enterpriseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businessman.enterprise_field
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer enterpriseField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businessman.has_management_work
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer hasManagementWork;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businessman.other
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String other;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businessman.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businessman.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businessman.is_delete
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column businessman.des
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String des;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businessman.id
     *
     * @return the value of businessman.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businessman.id
     *
     * @param id the value for businessman.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businessman.cid
     *
     * @return the value of businessman.cid
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businessman.cid
     *
     * @param cid the value for businessman.cid
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businessman.name
     *
     * @return the value of businessman.name
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businessman.name
     *
     * @param name the value for businessman.name
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businessman.img_dir
     *
     * @return the value of businessman.img_dir
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getImgDir() {
        return imgDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businessman.img_dir
     *
     * @param imgDir the value for businessman.img_dir
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setImgDir(String imgDir) {
        this.imgDir = imgDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businessman.img
     *
     * @return the value of businessman.img
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businessman.img
     *
     * @param img the value for businessman.img
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setImg(String img) {
        this.img = img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businessman.post
     *
     * @return the value of businessman.post
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businessman.post
     *
     * @param post the value for businessman.post
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setPost(String post) {
        this.post = post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businessman.sex
     *
     * @return the value of businessman.sex
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businessman.sex
     *
     * @param sex the value for businessman.sex
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businessman.age
     *
     * @return the value of businessman.age
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businessman.age
     *
     * @param age the value for businessman.age
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businessman.education
     *
     * @return the value of businessman.education
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businessman.education
     *
     * @param education the value for businessman.education
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setEducation(Integer education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businessman.school_type
     *
     * @return the value of businessman.school_type
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getSchoolType() {
        return schoolType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businessman.school_type
     *
     * @param schoolType the value for businessman.school_type
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setSchoolType(Integer schoolType) {
        this.schoolType = schoolType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businessman.school
     *
     * @return the value of businessman.school
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businessman.school
     *
     * @param school the value for businessman.school
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setSchool(String school) {
        this.school = school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businessman.school_type2
     *
     * @return the value of businessman.school_type2
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getSchoolType2() {
        return schoolType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businessman.school_type2
     *
     * @param schoolType2 the value for businessman.school_type2
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setSchoolType2(Integer schoolType2) {
        this.schoolType2 = schoolType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businessman.school2
     *
     * @return the value of businessman.school2
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getSchool2() {
        return school2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businessman.school2
     *
     * @param school2 the value for businessman.school2
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setSchool2(String school2) {
        this.school2 = school2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businessman.has_professional_certificate
     *
     * @return the value of businessman.has_professional_certificate
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getHasProfessionalCertificate() {
        return hasProfessionalCertificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businessman.has_professional_certificate
     *
     * @param hasProfessionalCertificate the value for businessman.has_professional_certificate
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setHasProfessionalCertificate(Integer hasProfessionalCertificate) {
        this.hasProfessionalCertificate = hasProfessionalCertificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businessman.professional_certificate
     *
     * @return the value of businessman.professional_certificate
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getProfessionalCertificate() {
        return professionalCertificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businessman.professional_certificate
     *
     * @param professionalCertificate the value for businessman.professional_certificate
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setProfessionalCertificate(String professionalCertificate) {
        this.professionalCertificate = professionalCertificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businessman.work_experience
     *
     * @return the value of businessman.work_experience
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getWorkExperience() {
        return workExperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businessman.work_experience
     *
     * @param workExperience the value for businessman.work_experience
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setWorkExperience(Integer workExperience) {
        this.workExperience = workExperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businessman.enterprise_type
     *
     * @return the value of businessman.enterprise_type
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getEnterpriseType() {
        return enterpriseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businessman.enterprise_type
     *
     * @param enterpriseType the value for businessman.enterprise_type
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setEnterpriseType(Integer enterpriseType) {
        this.enterpriseType = enterpriseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businessman.enterprise_field
     *
     * @return the value of businessman.enterprise_field
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getEnterpriseField() {
        return enterpriseField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businessman.enterprise_field
     *
     * @param enterpriseField the value for businessman.enterprise_field
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setEnterpriseField(Integer enterpriseField) {
        this.enterpriseField = enterpriseField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businessman.has_management_work
     *
     * @return the value of businessman.has_management_work
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getHasManagementWork() {
        return hasManagementWork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businessman.has_management_work
     *
     * @param hasManagementWork the value for businessman.has_management_work
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setHasManagementWork(Integer hasManagementWork) {
        this.hasManagementWork = hasManagementWork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businessman.other
     *
     * @return the value of businessman.other
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businessman.other
     *
     * @param other the value for businessman.other
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setOther(String other) {
        this.other = other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businessman.create_time
     *
     * @return the value of businessman.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businessman.create_time
     *
     * @param createTime the value for businessman.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businessman.update_time
     *
     * @return the value of businessman.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businessman.update_time
     *
     * @param updateTime the value for businessman.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businessman.is_delete
     *
     * @return the value of businessman.is_delete
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businessman.is_delete
     *
     * @param isDelete the value for businessman.is_delete
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column businessman.des
     *
     * @return the value of businessman.des
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column businessman.des
     *
     * @param des the value for businessman.des
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setDes(String des) {
        this.des = des;
    }
}