package com.jzt.api.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ChargeExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table charge
	 * @mbggenerated  Tue Mar 14 20:08:38 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table charge
	 * @mbggenerated  Tue Mar 14 20:08:38 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table charge
	 * @mbggenerated  Tue Mar 14 20:08:38 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge
	 * @mbggenerated  Tue Mar 14 20:08:38 CST 2017
	 */
	public ChargeExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge
	 * @mbggenerated  Tue Mar 14 20:08:38 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge
	 * @mbggenerated  Tue Mar 14 20:08:38 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge
	 * @mbggenerated  Tue Mar 14 20:08:38 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge
	 * @mbggenerated  Tue Mar 14 20:08:38 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge
	 * @mbggenerated  Tue Mar 14 20:08:38 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge
	 * @mbggenerated  Tue Mar 14 20:08:38 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge
	 * @mbggenerated  Tue Mar 14 20:08:38 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge
	 * @mbggenerated  Tue Mar 14 20:08:38 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge
	 * @mbggenerated  Tue Mar 14 20:08:38 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge
	 * @mbggenerated  Tue Mar 14 20:08:38 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table charge
	 * @mbggenerated  Tue Mar 14 20:08:38 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andChargeidIsNull() {
			addCriterion("chargeid is null");
			return (Criteria) this;
		}

		public Criteria andChargeidIsNotNull() {
			addCriterion("chargeid is not null");
			return (Criteria) this;
		}

		public Criteria andChargeidEqualTo(String value) {
			addCriterion("chargeid =", value, "chargeid");
			return (Criteria) this;
		}

		public Criteria andChargeidNotEqualTo(String value) {
			addCriterion("chargeid <>", value, "chargeid");
			return (Criteria) this;
		}

		public Criteria andChargeidGreaterThan(String value) {
			addCriterion("chargeid >", value, "chargeid");
			return (Criteria) this;
		}

		public Criteria andChargeidGreaterThanOrEqualTo(String value) {
			addCriterion("chargeid >=", value, "chargeid");
			return (Criteria) this;
		}

		public Criteria andChargeidLessThan(String value) {
			addCriterion("chargeid <", value, "chargeid");
			return (Criteria) this;
		}

		public Criteria andChargeidLessThanOrEqualTo(String value) {
			addCriterion("chargeid <=", value, "chargeid");
			return (Criteria) this;
		}

		public Criteria andChargeidLike(String value) {
			addCriterion("chargeid like", value, "chargeid");
			return (Criteria) this;
		}

		public Criteria andChargeidNotLike(String value) {
			addCriterion("chargeid not like", value, "chargeid");
			return (Criteria) this;
		}

		public Criteria andChargeidIn(List<String> values) {
			addCriterion("chargeid in", values, "chargeid");
			return (Criteria) this;
		}

		public Criteria andChargeidNotIn(List<String> values) {
			addCriterion("chargeid not in", values, "chargeid");
			return (Criteria) this;
		}

		public Criteria andChargeidBetween(String value1, String value2) {
			addCriterion("chargeid between", value1, value2, "chargeid");
			return (Criteria) this;
		}

		public Criteria andChargeidNotBetween(String value1, String value2) {
			addCriterion("chargeid not between", value1, value2, "chargeid");
			return (Criteria) this;
		}

		public Criteria andSubjectIsNull() {
			addCriterion("subject is null");
			return (Criteria) this;
		}

		public Criteria andSubjectIsNotNull() {
			addCriterion("subject is not null");
			return (Criteria) this;
		}

		public Criteria andSubjectEqualTo(String value) {
			addCriterion("subject =", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectNotEqualTo(String value) {
			addCriterion("subject <>", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectGreaterThan(String value) {
			addCriterion("subject >", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectGreaterThanOrEqualTo(String value) {
			addCriterion("subject >=", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectLessThan(String value) {
			addCriterion("subject <", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectLessThanOrEqualTo(String value) {
			addCriterion("subject <=", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectLike(String value) {
			addCriterion("subject like", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectNotLike(String value) {
			addCriterion("subject not like", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectIn(List<String> values) {
			addCriterion("subject in", values, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectNotIn(List<String> values) {
			addCriterion("subject not in", values, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectBetween(String value1, String value2) {
			addCriterion("subject between", value1, value2, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectNotBetween(String value1, String value2) {
			addCriterion("subject not between", value1, value2, "subject");
			return (Criteria) this;
		}

		public Criteria andChannelIsNull() {
			addCriterion("channel is null");
			return (Criteria) this;
		}

		public Criteria andChannelIsNotNull() {
			addCriterion("channel is not null");
			return (Criteria) this;
		}

		public Criteria andChannelEqualTo(String value) {
			addCriterion("channel =", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelNotEqualTo(String value) {
			addCriterion("channel <>", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelGreaterThan(String value) {
			addCriterion("channel >", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelGreaterThanOrEqualTo(String value) {
			addCriterion("channel >=", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelLessThan(String value) {
			addCriterion("channel <", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelLessThanOrEqualTo(String value) {
			addCriterion("channel <=", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelLike(String value) {
			addCriterion("channel like", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelNotLike(String value) {
			addCriterion("channel not like", value, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelIn(List<String> values) {
			addCriterion("channel in", values, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelNotIn(List<String> values) {
			addCriterion("channel not in", values, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelBetween(String value1, String value2) {
			addCriterion("channel between", value1, value2, "channel");
			return (Criteria) this;
		}

		public Criteria andChannelNotBetween(String value1, String value2) {
			addCriterion("channel not between", value1, value2, "channel");
			return (Criteria) this;
		}

		public Criteria andBodyIsNull() {
			addCriterion("body is null");
			return (Criteria) this;
		}

		public Criteria andBodyIsNotNull() {
			addCriterion("body is not null");
			return (Criteria) this;
		}

		public Criteria andBodyEqualTo(String value) {
			addCriterion("body =", value, "body");
			return (Criteria) this;
		}

		public Criteria andBodyNotEqualTo(String value) {
			addCriterion("body <>", value, "body");
			return (Criteria) this;
		}

		public Criteria andBodyGreaterThan(String value) {
			addCriterion("body >", value, "body");
			return (Criteria) this;
		}

		public Criteria andBodyGreaterThanOrEqualTo(String value) {
			addCriterion("body >=", value, "body");
			return (Criteria) this;
		}

		public Criteria andBodyLessThan(String value) {
			addCriterion("body <", value, "body");
			return (Criteria) this;
		}

		public Criteria andBodyLessThanOrEqualTo(String value) {
			addCriterion("body <=", value, "body");
			return (Criteria) this;
		}

		public Criteria andBodyLike(String value) {
			addCriterion("body like", value, "body");
			return (Criteria) this;
		}

		public Criteria andBodyNotLike(String value) {
			addCriterion("body not like", value, "body");
			return (Criteria) this;
		}

		public Criteria andBodyIn(List<String> values) {
			addCriterion("body in", values, "body");
			return (Criteria) this;
		}

		public Criteria andBodyNotIn(List<String> values) {
			addCriterion("body not in", values, "body");
			return (Criteria) this;
		}

		public Criteria andBodyBetween(String value1, String value2) {
			addCriterion("body between", value1, value2, "body");
			return (Criteria) this;
		}

		public Criteria andBodyNotBetween(String value1, String value2) {
			addCriterion("body not between", value1, value2, "body");
			return (Criteria) this;
		}

		public Criteria andClientipIsNull() {
			addCriterion("clientip is null");
			return (Criteria) this;
		}

		public Criteria andClientipIsNotNull() {
			addCriterion("clientip is not null");
			return (Criteria) this;
		}

		public Criteria andClientipEqualTo(String value) {
			addCriterion("clientip =", value, "clientip");
			return (Criteria) this;
		}

		public Criteria andClientipNotEqualTo(String value) {
			addCriterion("clientip <>", value, "clientip");
			return (Criteria) this;
		}

		public Criteria andClientipGreaterThan(String value) {
			addCriterion("clientip >", value, "clientip");
			return (Criteria) this;
		}

		public Criteria andClientipGreaterThanOrEqualTo(String value) {
			addCriterion("clientip >=", value, "clientip");
			return (Criteria) this;
		}

		public Criteria andClientipLessThan(String value) {
			addCriterion("clientip <", value, "clientip");
			return (Criteria) this;
		}

		public Criteria andClientipLessThanOrEqualTo(String value) {
			addCriterion("clientip <=", value, "clientip");
			return (Criteria) this;
		}

		public Criteria andClientipLike(String value) {
			addCriterion("clientip like", value, "clientip");
			return (Criteria) this;
		}

		public Criteria andClientipNotLike(String value) {
			addCriterion("clientip not like", value, "clientip");
			return (Criteria) this;
		}

		public Criteria andClientipIn(List<String> values) {
			addCriterion("clientip in", values, "clientip");
			return (Criteria) this;
		}

		public Criteria andClientipNotIn(List<String> values) {
			addCriterion("clientip not in", values, "clientip");
			return (Criteria) this;
		}

		public Criteria andClientipBetween(String value1, String value2) {
			addCriterion("clientip between", value1, value2, "clientip");
			return (Criteria) this;
		}

		public Criteria andClientipNotBetween(String value1, String value2) {
			addCriterion("clientip not between", value1, value2, "clientip");
			return (Criteria) this;
		}

		public Criteria andAmountIsNull() {
			addCriterion("amount is null");
			return (Criteria) this;
		}

		public Criteria andAmountIsNotNull() {
			addCriterion("amount is not null");
			return (Criteria) this;
		}

		public Criteria andAmountEqualTo(Integer value) {
			addCriterion("amount =", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotEqualTo(Integer value) {
			addCriterion("amount <>", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThan(Integer value) {
			addCriterion("amount >", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThanOrEqualTo(Integer value) {
			addCriterion("amount >=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThan(Integer value) {
			addCriterion("amount <", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThanOrEqualTo(Integer value) {
			addCriterion("amount <=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountIn(List<Integer> values) {
			addCriterion("amount in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotIn(List<Integer> values) {
			addCriterion("amount not in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountBetween(Integer value1, Integer value2) {
			addCriterion("amount between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotBetween(Integer value1, Integer value2) {
			addCriterion("amount not between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andCurrencyIsNull() {
			addCriterion("currency is null");
			return (Criteria) this;
		}

		public Criteria andCurrencyIsNotNull() {
			addCriterion("currency is not null");
			return (Criteria) this;
		}

		public Criteria andCurrencyEqualTo(String value) {
			addCriterion("currency =", value, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyNotEqualTo(String value) {
			addCriterion("currency <>", value, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyGreaterThan(String value) {
			addCriterion("currency >", value, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyGreaterThanOrEqualTo(String value) {
			addCriterion("currency >=", value, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyLessThan(String value) {
			addCriterion("currency <", value, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyLessThanOrEqualTo(String value) {
			addCriterion("currency <=", value, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyLike(String value) {
			addCriterion("currency like", value, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyNotLike(String value) {
			addCriterion("currency not like", value, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyIn(List<String> values) {
			addCriterion("currency in", values, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyNotIn(List<String> values) {
			addCriterion("currency not in", values, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyBetween(String value1, String value2) {
			addCriterion("currency between", value1, value2, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyNotBetween(String value1, String value2) {
			addCriterion("currency not between", value1, value2, "currency");
			return (Criteria) this;
		}

		public Criteria andMessageIsNull() {
			addCriterion("message is null");
			return (Criteria) this;
		}

		public Criteria andMessageIsNotNull() {
			addCriterion("message is not null");
			return (Criteria) this;
		}

		public Criteria andMessageEqualTo(String value) {
			addCriterion("message =", value, "message");
			return (Criteria) this;
		}

		public Criteria andMessageNotEqualTo(String value) {
			addCriterion("message <>", value, "message");
			return (Criteria) this;
		}

		public Criteria andMessageGreaterThan(String value) {
			addCriterion("message >", value, "message");
			return (Criteria) this;
		}

		public Criteria andMessageGreaterThanOrEqualTo(String value) {
			addCriterion("message >=", value, "message");
			return (Criteria) this;
		}

		public Criteria andMessageLessThan(String value) {
			addCriterion("message <", value, "message");
			return (Criteria) this;
		}

		public Criteria andMessageLessThanOrEqualTo(String value) {
			addCriterion("message <=", value, "message");
			return (Criteria) this;
		}

		public Criteria andMessageLike(String value) {
			addCriterion("message like", value, "message");
			return (Criteria) this;
		}

		public Criteria andMessageNotLike(String value) {
			addCriterion("message not like", value, "message");
			return (Criteria) this;
		}

		public Criteria andMessageIn(List<String> values) {
			addCriterion("message in", values, "message");
			return (Criteria) this;
		}

		public Criteria andMessageNotIn(List<String> values) {
			addCriterion("message not in", values, "message");
			return (Criteria) this;
		}

		public Criteria andMessageBetween(String value1, String value2) {
			addCriterion("message between", value1, value2, "message");
			return (Criteria) this;
		}

		public Criteria andMessageNotBetween(String value1, String value2) {
			addCriterion("message not between", value1, value2, "message");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("address is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("address is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("address =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("address <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("address >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("address >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("address <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("address <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("address like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("address not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("address in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("address not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("address between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("address not between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andProductidIsNull() {
			addCriterion("productid is null");
			return (Criteria) this;
		}

		public Criteria andProductidIsNotNull() {
			addCriterion("productid is not null");
			return (Criteria) this;
		}

		public Criteria andProductidEqualTo(String value) {
			addCriterion("productid =", value, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidNotEqualTo(String value) {
			addCriterion("productid <>", value, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidGreaterThan(String value) {
			addCriterion("productid >", value, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidGreaterThanOrEqualTo(String value) {
			addCriterion("productid >=", value, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidLessThan(String value) {
			addCriterion("productid <", value, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidLessThanOrEqualTo(String value) {
			addCriterion("productid <=", value, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidLike(String value) {
			addCriterion("productid like", value, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidNotLike(String value) {
			addCriterion("productid not like", value, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidIn(List<String> values) {
			addCriterion("productid in", values, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidNotIn(List<String> values) {
			addCriterion("productid not in", values, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidBetween(String value1, String value2) {
			addCriterion("productid between", value1, value2, "productid");
			return (Criteria) this;
		}

		public Criteria andProductidNotBetween(String value1, String value2) {
			addCriterion("productid not between", value1, value2, "productid");
			return (Criteria) this;
		}

		public Criteria andOrdernoIsNull() {
			addCriterion("orderno is null");
			return (Criteria) this;
		}

		public Criteria andOrdernoIsNotNull() {
			addCriterion("orderno is not null");
			return (Criteria) this;
		}

		public Criteria andOrdernoEqualTo(String value) {
			addCriterion("orderno =", value, "orderno");
			return (Criteria) this;
		}

		public Criteria andOrdernoNotEqualTo(String value) {
			addCriterion("orderno <>", value, "orderno");
			return (Criteria) this;
		}

		public Criteria andOrdernoGreaterThan(String value) {
			addCriterion("orderno >", value, "orderno");
			return (Criteria) this;
		}

		public Criteria andOrdernoGreaterThanOrEqualTo(String value) {
			addCriterion("orderno >=", value, "orderno");
			return (Criteria) this;
		}

		public Criteria andOrdernoLessThan(String value) {
			addCriterion("orderno <", value, "orderno");
			return (Criteria) this;
		}

		public Criteria andOrdernoLessThanOrEqualTo(String value) {
			addCriterion("orderno <=", value, "orderno");
			return (Criteria) this;
		}

		public Criteria andOrdernoLike(String value) {
			addCriterion("orderno like", value, "orderno");
			return (Criteria) this;
		}

		public Criteria andOrdernoNotLike(String value) {
			addCriterion("orderno not like", value, "orderno");
			return (Criteria) this;
		}

		public Criteria andOrdernoIn(List<String> values) {
			addCriterion("orderno in", values, "orderno");
			return (Criteria) this;
		}

		public Criteria andOrdernoNotIn(List<String> values) {
			addCriterion("orderno not in", values, "orderno");
			return (Criteria) this;
		}

		public Criteria andOrdernoBetween(String value1, String value2) {
			addCriterion("orderno between", value1, value2, "orderno");
			return (Criteria) this;
		}

		public Criteria andOrdernoNotBetween(String value1, String value2) {
			addCriterion("orderno not between", value1, value2, "orderno");
			return (Criteria) this;
		}

		public Criteria andCreatedIsNull() {
			addCriterion("created is null");
			return (Criteria) this;
		}

		public Criteria andCreatedIsNotNull() {
			addCriterion("created is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedEqualTo(String value) {
			addCriterion("created =", value, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedNotEqualTo(String value) {
			addCriterion("created <>", value, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedGreaterThan(String value) {
			addCriterion("created >", value, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedGreaterThanOrEqualTo(String value) {
			addCriterion("created >=", value, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedLessThan(String value) {
			addCriterion("created <", value, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedLessThanOrEqualTo(String value) {
			addCriterion("created <=", value, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedLike(String value) {
			addCriterion("created like", value, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedNotLike(String value) {
			addCriterion("created not like", value, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedIn(List<String> values) {
			addCriterion("created in", values, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedNotIn(List<String> values) {
			addCriterion("created not in", values, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedBetween(String value1, String value2) {
			addCriterion("created between", value1, value2, "created");
			return (Criteria) this;
		}

		public Criteria andCreatedNotBetween(String value1, String value2) {
			addCriterion("created not between", value1, value2, "created");
			return (Criteria) this;
		}

		public Criteria andPaidIsNull() {
			addCriterion("paid is null");
			return (Criteria) this;
		}

		public Criteria andPaidIsNotNull() {
			addCriterion("paid is not null");
			return (Criteria) this;
		}

		public Criteria andPaidEqualTo(String value) {
			addCriterion("paid =", value, "paid");
			return (Criteria) this;
		}

		public Criteria andPaidNotEqualTo(String value) {
			addCriterion("paid <>", value, "paid");
			return (Criteria) this;
		}

		public Criteria andPaidGreaterThan(String value) {
			addCriterion("paid >", value, "paid");
			return (Criteria) this;
		}

		public Criteria andPaidGreaterThanOrEqualTo(String value) {
			addCriterion("paid >=", value, "paid");
			return (Criteria) this;
		}

		public Criteria andPaidLessThan(String value) {
			addCriterion("paid <", value, "paid");
			return (Criteria) this;
		}

		public Criteria andPaidLessThanOrEqualTo(String value) {
			addCriterion("paid <=", value, "paid");
			return (Criteria) this;
		}

		public Criteria andPaidLike(String value) {
			addCriterion("paid like", value, "paid");
			return (Criteria) this;
		}

		public Criteria andPaidNotLike(String value) {
			addCriterion("paid not like", value, "paid");
			return (Criteria) this;
		}

		public Criteria andPaidIn(List<String> values) {
			addCriterion("paid in", values, "paid");
			return (Criteria) this;
		}

		public Criteria andPaidNotIn(List<String> values) {
			addCriterion("paid not in", values, "paid");
			return (Criteria) this;
		}

		public Criteria andPaidBetween(String value1, String value2) {
			addCriterion("paid between", value1, value2, "paid");
			return (Criteria) this;
		}

		public Criteria andPaidNotBetween(String value1, String value2) {
			addCriterion("paid not between", value1, value2, "paid");
			return (Criteria) this;
		}

		public Criteria andRefundedIsNull() {
			addCriterion("refunded is null");
			return (Criteria) this;
		}

		public Criteria andRefundedIsNotNull() {
			addCriterion("refunded is not null");
			return (Criteria) this;
		}

		public Criteria andRefundedEqualTo(String value) {
			addCriterion("refunded =", value, "refunded");
			return (Criteria) this;
		}

		public Criteria andRefundedNotEqualTo(String value) {
			addCriterion("refunded <>", value, "refunded");
			return (Criteria) this;
		}

		public Criteria andRefundedGreaterThan(String value) {
			addCriterion("refunded >", value, "refunded");
			return (Criteria) this;
		}

		public Criteria andRefundedGreaterThanOrEqualTo(String value) {
			addCriterion("refunded >=", value, "refunded");
			return (Criteria) this;
		}

		public Criteria andRefundedLessThan(String value) {
			addCriterion("refunded <", value, "refunded");
			return (Criteria) this;
		}

		public Criteria andRefundedLessThanOrEqualTo(String value) {
			addCriterion("refunded <=", value, "refunded");
			return (Criteria) this;
		}

		public Criteria andRefundedLike(String value) {
			addCriterion("refunded like", value, "refunded");
			return (Criteria) this;
		}

		public Criteria andRefundedNotLike(String value) {
			addCriterion("refunded not like", value, "refunded");
			return (Criteria) this;
		}

		public Criteria andRefundedIn(List<String> values) {
			addCriterion("refunded in", values, "refunded");
			return (Criteria) this;
		}

		public Criteria andRefundedNotIn(List<String> values) {
			addCriterion("refunded not in", values, "refunded");
			return (Criteria) this;
		}

		public Criteria andRefundedBetween(String value1, String value2) {
			addCriterion("refunded between", value1, value2, "refunded");
			return (Criteria) this;
		}

		public Criteria andRefundedNotBetween(String value1, String value2) {
			addCriterion("refunded not between", value1, value2, "refunded");
			return (Criteria) this;
		}

		public Criteria andAppidIsNull() {
			addCriterion("appid is null");
			return (Criteria) this;
		}

		public Criteria andAppidIsNotNull() {
			addCriterion("appid is not null");
			return (Criteria) this;
		}

		public Criteria andAppidEqualTo(String value) {
			addCriterion("appid =", value, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidNotEqualTo(String value) {
			addCriterion("appid <>", value, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidGreaterThan(String value) {
			addCriterion("appid >", value, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidGreaterThanOrEqualTo(String value) {
			addCriterion("appid >=", value, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidLessThan(String value) {
			addCriterion("appid <", value, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidLessThanOrEqualTo(String value) {
			addCriterion("appid <=", value, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidLike(String value) {
			addCriterion("appid like", value, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidNotLike(String value) {
			addCriterion("appid not like", value, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidIn(List<String> values) {
			addCriterion("appid in", values, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidNotIn(List<String> values) {
			addCriterion("appid not in", values, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidBetween(String value1, String value2) {
			addCriterion("appid between", value1, value2, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidNotBetween(String value1, String value2) {
			addCriterion("appid not between", value1, value2, "appid");
			return (Criteria) this;
		}

		public Criteria andTimeexpireIsNull() {
			addCriterion("timeexpire is null");
			return (Criteria) this;
		}

		public Criteria andTimeexpireIsNotNull() {
			addCriterion("timeexpire is not null");
			return (Criteria) this;
		}

		public Criteria andTimeexpireEqualTo(String value) {
			addCriterion("timeexpire =", value, "timeexpire");
			return (Criteria) this;
		}

		public Criteria andTimeexpireNotEqualTo(String value) {
			addCriterion("timeexpire <>", value, "timeexpire");
			return (Criteria) this;
		}

		public Criteria andTimeexpireGreaterThan(String value) {
			addCriterion("timeexpire >", value, "timeexpire");
			return (Criteria) this;
		}

		public Criteria andTimeexpireGreaterThanOrEqualTo(String value) {
			addCriterion("timeexpire >=", value, "timeexpire");
			return (Criteria) this;
		}

		public Criteria andTimeexpireLessThan(String value) {
			addCriterion("timeexpire <", value, "timeexpire");
			return (Criteria) this;
		}

		public Criteria andTimeexpireLessThanOrEqualTo(String value) {
			addCriterion("timeexpire <=", value, "timeexpire");
			return (Criteria) this;
		}

		public Criteria andTimeexpireLike(String value) {
			addCriterion("timeexpire like", value, "timeexpire");
			return (Criteria) this;
		}

		public Criteria andTimeexpireNotLike(String value) {
			addCriterion("timeexpire not like", value, "timeexpire");
			return (Criteria) this;
		}

		public Criteria andTimeexpireIn(List<String> values) {
			addCriterion("timeexpire in", values, "timeexpire");
			return (Criteria) this;
		}

		public Criteria andTimeexpireNotIn(List<String> values) {
			addCriterion("timeexpire not in", values, "timeexpire");
			return (Criteria) this;
		}

		public Criteria andTimeexpireBetween(String value1, String value2) {
			addCriterion("timeexpire between", value1, value2, "timeexpire");
			return (Criteria) this;
		}

		public Criteria andTimeexpireNotBetween(String value1, String value2) {
			addCriterion("timeexpire not between", value1, value2, "timeexpire");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNull() {
			addCriterion("description is null");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNotNull() {
			addCriterion("description is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("description =", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("description <>", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("description >", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("description >=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThan(String value) {
			addCriterion("description <", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("description <=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLike(String value) {
			addCriterion("description like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotLike(String value) {
			addCriterion("description not like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionIn(List<String> values) {
			addCriterion("description in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotIn(List<String> values) {
			addCriterion("description not in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("description between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("description not between", value1, value2,
					"description");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIsNull() {
			addCriterion("createtime is null");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIsNotNull() {
			addCriterion("createtime is not null");
			return (Criteria) this;
		}

		public Criteria andCreatetimeEqualTo(Date value) {
			addCriterion("createtime =", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotEqualTo(Date value) {
			addCriterion("createtime <>", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeGreaterThan(Date value) {
			addCriterion("createtime >", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("createtime >=", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeLessThan(Date value) {
			addCriterion("createtime <", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
			addCriterion("createtime <=", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIn(List<Date> values) {
			addCriterion("createtime in", values, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotIn(List<Date> values) {
			addCriterion("createtime not in", values, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeBetween(Date value1, Date value2) {
			addCriterion("createtime between", value1, value2, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
			addCriterion("createtime not between", value1, value2, "createtime");
			return (Criteria) this;
		}

		public Criteria andModifytimeIsNull() {
			addCriterion("modifytime is null");
			return (Criteria) this;
		}

		public Criteria andModifytimeIsNotNull() {
			addCriterion("modifytime is not null");
			return (Criteria) this;
		}

		public Criteria andModifytimeEqualTo(Date value) {
			addCriterion("modifytime =", value, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeNotEqualTo(Date value) {
			addCriterion("modifytime <>", value, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeGreaterThan(Date value) {
			addCriterion("modifytime >", value, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeGreaterThanOrEqualTo(Date value) {
			addCriterion("modifytime >=", value, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeLessThan(Date value) {
			addCriterion("modifytime <", value, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeLessThanOrEqualTo(Date value) {
			addCriterion("modifytime <=", value, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeIn(List<Date> values) {
			addCriterion("modifytime in", values, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeNotIn(List<Date> values) {
			addCriterion("modifytime not in", values, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeBetween(Date value1, Date value2) {
			addCriterion("modifytime between", value1, value2, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeNotBetween(Date value1, Date value2) {
			addCriterion("modifytime not between", value1, value2, "modifytime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table charge
	 * @mbggenerated  Tue Mar 14 20:08:38 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table charge
     *
     * @mbggenerated do_not_delete_during_merge Sun Mar 12 23:14:32 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}