package com.jzt.api.domain;

public class CompanyWithBLOBs extends Company {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.business_scope
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String businessScope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.registered_capital_change
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String registeredCapitalChange;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.business_scope
     *
     * @return the value of company.business_scope
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getBusinessScope() {
        return businessScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.business_scope
     *
     * @param businessScope the value for company.business_scope
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setBusinessScope(String businessScope) {
        this.businessScope = businessScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.registered_capital_change
     *
     * @return the value of company.registered_capital_change
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getRegisteredCapitalChange() {
        return registeredCapitalChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.registered_capital_change
     *
     * @param registeredCapitalChange the value for company.registered_capital_change
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setRegisteredCapitalChange(String registeredCapitalChange) {
        this.registeredCapitalChange = registeredCapitalChange;
    }
}