package com.jzt.api.domain;

import java.util.Date;

public class ExposureUserAgree {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exposure_user_agree.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exposure_user_agree.user_id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exposure_user_agree.exposure_id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer exposureId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exposure_user_agree.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exposure_user_agree.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exposure_user_agree.id
     *
     * @return the value of exposure_user_agree.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exposure_user_agree.id
     *
     * @param id the value for exposure_user_agree.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exposure_user_agree.user_id
     *
     * @return the value of exposure_user_agree.user_id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exposure_user_agree.user_id
     *
     * @param userId the value for exposure_user_agree.user_id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exposure_user_agree.exposure_id
     *
     * @return the value of exposure_user_agree.exposure_id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getExposureId() {
        return exposureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exposure_user_agree.exposure_id
     *
     * @param exposureId the value for exposure_user_agree.exposure_id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setExposureId(Integer exposureId) {
        this.exposureId = exposureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exposure_user_agree.create_time
     *
     * @return the value of exposure_user_agree.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exposure_user_agree.create_time
     *
     * @param createTime the value for exposure_user_agree.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exposure_user_agree.update_time
     *
     * @return the value of exposure_user_agree.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exposure_user_agree.update_time
     *
     * @param updateTime the value for exposure_user_agree.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}