package com.jzt.api.domain;

import java.util.Date;

public class ExposureImage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exposure_image.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exposure_image.eid
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exposure_image.url
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exposure_image.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exposure_image.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exposure_image.id
     *
     * @return the value of exposure_image.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exposure_image.id
     *
     * @param id the value for exposure_image.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exposure_image.eid
     *
     * @return the value of exposure_image.eid
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exposure_image.eid
     *
     * @param eid the value for exposure_image.eid
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exposure_image.url
     *
     * @return the value of exposure_image.url
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exposure_image.url
     *
     * @param url the value for exposure_image.url
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exposure_image.create_time
     *
     * @return the value of exposure_image.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exposure_image.create_time
     *
     * @param createTime the value for exposure_image.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exposure_image.update_time
     *
     * @return the value of exposure_image.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exposure_image.update_time
     *
     * @param updateTime the value for exposure_image.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}