package com.jzt.api.domain;

import java.util.Date;

public class HotNewsApproval {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_news_approval.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_news_approval.nId
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer nid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_news_approval.hotpoint
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Float hotpoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_news_approval.isCheck
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String ischeck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_news_approval.related_admin
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer relatedAdmin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_news_approval.publish_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Date publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_news_approval.idx
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer idx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_news_approval.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_news_approval.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_news_approval.id
     *
     * @return the value of hot_news_approval.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_news_approval.id
     *
     * @param id the value for hot_news_approval.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_news_approval.nId
     *
     * @return the value of hot_news_approval.nId
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getNid() {
        return nid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_news_approval.nId
     *
     * @param nid the value for hot_news_approval.nId
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setNid(Integer nid) {
        this.nid = nid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_news_approval.hotpoint
     *
     * @return the value of hot_news_approval.hotpoint
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Float getHotpoint() {
        return hotpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_news_approval.hotpoint
     *
     * @param hotpoint the value for hot_news_approval.hotpoint
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setHotpoint(Float hotpoint) {
        this.hotpoint = hotpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_news_approval.isCheck
     *
     * @return the value of hot_news_approval.isCheck
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getIscheck() {
        return ischeck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_news_approval.isCheck
     *
     * @param ischeck the value for hot_news_approval.isCheck
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setIscheck(String ischeck) {
        this.ischeck = ischeck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_news_approval.related_admin
     *
     * @return the value of hot_news_approval.related_admin
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getRelatedAdmin() {
        return relatedAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_news_approval.related_admin
     *
     * @param relatedAdmin the value for hot_news_approval.related_admin
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setRelatedAdmin(Integer relatedAdmin) {
        this.relatedAdmin = relatedAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_news_approval.publish_time
     *
     * @return the value of hot_news_approval.publish_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_news_approval.publish_time
     *
     * @param publishTime the value for hot_news_approval.publish_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_news_approval.idx
     *
     * @return the value of hot_news_approval.idx
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_news_approval.idx
     *
     * @param idx the value for hot_news_approval.idx
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setIdx(Integer idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_news_approval.create_time
     *
     * @return the value of hot_news_approval.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_news_approval.create_time
     *
     * @param createTime the value for hot_news_approval.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_news_approval.update_time
     *
     * @return the value of hot_news_approval.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_news_approval.update_time
     *
     * @param updateTime the value for hot_news_approval.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}