package com.jzt.api.domain;

import java.util.Date;

public class HotPlatApproval {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_plat_approval.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_plat_approval.pId
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_plat_approval.hotpoint
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer hotpoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_plat_approval.isCheck
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String ischeck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_plat_approval.related_admin
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer relatedAdmin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_plat_approval.publish_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Date publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_plat_approval.idx
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer idx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_plat_approval.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_plat_approval.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_plat_approval.id
     *
     * @return the value of hot_plat_approval.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_plat_approval.id
     *
     * @param id the value for hot_plat_approval.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_plat_approval.pId
     *
     * @return the value of hot_plat_approval.pId
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_plat_approval.pId
     *
     * @param pid the value for hot_plat_approval.pId
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_plat_approval.hotpoint
     *
     * @return the value of hot_plat_approval.hotpoint
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getHotpoint() {
        return hotpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_plat_approval.hotpoint
     *
     * @param hotpoint the value for hot_plat_approval.hotpoint
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setHotpoint(Integer hotpoint) {
        this.hotpoint = hotpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_plat_approval.isCheck
     *
     * @return the value of hot_plat_approval.isCheck
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getIscheck() {
        return ischeck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_plat_approval.isCheck
     *
     * @param ischeck the value for hot_plat_approval.isCheck
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setIscheck(String ischeck) {
        this.ischeck = ischeck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_plat_approval.related_admin
     *
     * @return the value of hot_plat_approval.related_admin
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getRelatedAdmin() {
        return relatedAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_plat_approval.related_admin
     *
     * @param relatedAdmin the value for hot_plat_approval.related_admin
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setRelatedAdmin(Integer relatedAdmin) {
        this.relatedAdmin = relatedAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_plat_approval.publish_time
     *
     * @return the value of hot_plat_approval.publish_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_plat_approval.publish_time
     *
     * @param publishTime the value for hot_plat_approval.publish_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_plat_approval.idx
     *
     * @return the value of hot_plat_approval.idx
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_plat_approval.idx
     *
     * @param idx the value for hot_plat_approval.idx
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setIdx(Integer idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_plat_approval.create_time
     *
     * @return the value of hot_plat_approval.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_plat_approval.create_time
     *
     * @param createTime the value for hot_plat_approval.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_plat_approval.update_time
     *
     * @return the value of hot_plat_approval.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_plat_approval.update_time
     *
     * @param updateTime the value for hot_plat_approval.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}