package com.jzt.api.domain;

import java.util.Date;

public class MessageInfo extends BaseDomain{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_info.id
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_info.user_id
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_info.send_time
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_info.title
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_info.content
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_info.icon
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_info.type
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_info.is_read
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    private Integer isRead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_info.is_delete
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_info.create_time
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_info.update_time
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_info.id
     *
     * @return the value of message_info.id
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_info.id
     *
     * @param id the value for message_info.id
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_info.user_id
     *
     * @return the value of message_info.user_id
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_info.user_id
     *
     * @param userId the value for message_info.user_id
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_info.send_time
     *
     * @return the value of message_info.send_time
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_info.send_time
     *
     * @param sendTime the value for message_info.send_time
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_info.title
     *
     * @return the value of message_info.title
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_info.title
     *
     * @param title the value for message_info.title
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_info.content
     *
     * @return the value of message_info.content
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_info.content
     *
     * @param content the value for message_info.content
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_info.icon
     *
     * @return the value of message_info.icon
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_info.icon
     *
     * @param icon the value for message_info.icon
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_info.type
     *
     * @return the value of message_info.type
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_info.type
     *
     * @param type the value for message_info.type
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_info.is_read
     *
     * @return the value of message_info.is_read
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    public Integer getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_info.is_read
     *
     * @param isRead the value for message_info.is_read
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    public void setIsRead(Integer isRead) {
        this.isRead = isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_info.is_delete
     *
     * @return the value of message_info.is_delete
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_info.is_delete
     *
     * @param isDelete the value for message_info.is_delete
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_info.create_time
     *
     * @return the value of message_info.create_time
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_info.create_time
     *
     * @param createTime the value for message_info.create_time
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_info.update_time
     *
     * @return the value of message_info.update_time
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_info.update_time
     *
     * @param updateTime the value for message_info.update_time
     *
     * @mbggenerated Sun Mar 26 09:22:45 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}