package com.jzt.api.domain;

public class P2pPlatWithBLOBs extends P2pPlat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_plat.manage_fee_detail
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String manageFeeDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_plat.prepaid_fee_detail
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String prepaidFeeDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_plat.cash_withdrawal_fee
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String cashWithdrawalFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_plat.cash_withdrawal_fee_detail
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String cashWithdrawalFeeDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_plat.transfer_fee
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String transferFee;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_plat.manage_fee_detail
     *
     * @return the value of p2p_plat.manage_fee_detail
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getManageFeeDetail() {
        return manageFeeDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_plat.manage_fee_detail
     *
     * @param manageFeeDetail the value for p2p_plat.manage_fee_detail
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setManageFeeDetail(String manageFeeDetail) {
        this.manageFeeDetail = manageFeeDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_plat.prepaid_fee_detail
     *
     * @return the value of p2p_plat.prepaid_fee_detail
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getPrepaidFeeDetail() {
        return prepaidFeeDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_plat.prepaid_fee_detail
     *
     * @param prepaidFeeDetail the value for p2p_plat.prepaid_fee_detail
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setPrepaidFeeDetail(String prepaidFeeDetail) {
        this.prepaidFeeDetail = prepaidFeeDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_plat.cash_withdrawal_fee
     *
     * @return the value of p2p_plat.cash_withdrawal_fee
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getCashWithdrawalFee() {
        return cashWithdrawalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_plat.cash_withdrawal_fee
     *
     * @param cashWithdrawalFee the value for p2p_plat.cash_withdrawal_fee
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setCashWithdrawalFee(String cashWithdrawalFee) {
        this.cashWithdrawalFee = cashWithdrawalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_plat.cash_withdrawal_fee_detail
     *
     * @return the value of p2p_plat.cash_withdrawal_fee_detail
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getCashWithdrawalFeeDetail() {
        return cashWithdrawalFeeDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_plat.cash_withdrawal_fee_detail
     *
     * @param cashWithdrawalFeeDetail the value for p2p_plat.cash_withdrawal_fee_detail
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setCashWithdrawalFeeDetail(String cashWithdrawalFeeDetail) {
        this.cashWithdrawalFeeDetail = cashWithdrawalFeeDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_plat.transfer_fee
     *
     * @return the value of p2p_plat.transfer_fee
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getTransferFee() {
        return transferFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_plat.transfer_fee
     *
     * @param transferFee the value for p2p_plat.transfer_fee
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setTransferFee(String transferFee) {
        this.transferFee = transferFee;
    }
}