package com.jzt.api.domain;

import java.util.Date;

public class P2pTrend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_trend.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_trend.plat_id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer platId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_trend.date
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_trend.turnover
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Float turnover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_trend.interest_rate
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Float interestRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_trend.investment_amount
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Float investmentAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_trend.borrow_amount
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Float borrowAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_trend.num_investment
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer numInvestment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_trend.num_borrower
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer numBorrower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_trend.average_loan_period
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Float averageLoanPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_trend.loan_bid
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer loanBid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_trend.time_for_full_bid
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Float timeForFullBid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_trend.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p2p_trend.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_trend.id
     *
     * @return the value of p2p_trend.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_trend.id
     *
     * @param id the value for p2p_trend.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_trend.plat_id
     *
     * @return the value of p2p_trend.plat_id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getPlatId() {
        return platId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_trend.plat_id
     *
     * @param platId the value for p2p_trend.plat_id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setPlatId(Integer platId) {
        this.platId = platId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_trend.date
     *
     * @return the value of p2p_trend.date
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_trend.date
     *
     * @param date the value for p2p_trend.date
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_trend.turnover
     *
     * @return the value of p2p_trend.turnover
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Float getTurnover() {
        return turnover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_trend.turnover
     *
     * @param turnover the value for p2p_trend.turnover
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setTurnover(Float turnover) {
        this.turnover = turnover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_trend.interest_rate
     *
     * @return the value of p2p_trend.interest_rate
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Float getInterestRate() {
        return interestRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_trend.interest_rate
     *
     * @param interestRate the value for p2p_trend.interest_rate
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setInterestRate(Float interestRate) {
        this.interestRate = interestRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_trend.investment_amount
     *
     * @return the value of p2p_trend.investment_amount
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Float getInvestmentAmount() {
        return investmentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_trend.investment_amount
     *
     * @param investmentAmount the value for p2p_trend.investment_amount
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setInvestmentAmount(Float investmentAmount) {
        this.investmentAmount = investmentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_trend.borrow_amount
     *
     * @return the value of p2p_trend.borrow_amount
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Float getBorrowAmount() {
        return borrowAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_trend.borrow_amount
     *
     * @param borrowAmount the value for p2p_trend.borrow_amount
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setBorrowAmount(Float borrowAmount) {
        this.borrowAmount = borrowAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_trend.num_investment
     *
     * @return the value of p2p_trend.num_investment
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getNumInvestment() {
        return numInvestment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_trend.num_investment
     *
     * @param numInvestment the value for p2p_trend.num_investment
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setNumInvestment(Integer numInvestment) {
        this.numInvestment = numInvestment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_trend.num_borrower
     *
     * @return the value of p2p_trend.num_borrower
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getNumBorrower() {
        return numBorrower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_trend.num_borrower
     *
     * @param numBorrower the value for p2p_trend.num_borrower
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setNumBorrower(Integer numBorrower) {
        this.numBorrower = numBorrower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_trend.average_loan_period
     *
     * @return the value of p2p_trend.average_loan_period
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Float getAverageLoanPeriod() {
        return averageLoanPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_trend.average_loan_period
     *
     * @param averageLoanPeriod the value for p2p_trend.average_loan_period
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setAverageLoanPeriod(Float averageLoanPeriod) {
        this.averageLoanPeriod = averageLoanPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_trend.loan_bid
     *
     * @return the value of p2p_trend.loan_bid
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getLoanBid() {
        return loanBid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_trend.loan_bid
     *
     * @param loanBid the value for p2p_trend.loan_bid
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setLoanBid(Integer loanBid) {
        this.loanBid = loanBid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_trend.time_for_full_bid
     *
     * @return the value of p2p_trend.time_for_full_bid
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Float getTimeForFullBid() {
        return timeForFullBid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_trend.time_for_full_bid
     *
     * @param timeForFullBid the value for p2p_trend.time_for_full_bid
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setTimeForFullBid(Float timeForFullBid) {
        this.timeForFullBid = timeForFullBid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_trend.create_time
     *
     * @return the value of p2p_trend.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_trend.create_time
     *
     * @param createTime the value for p2p_trend.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p2p_trend.update_time
     *
     * @return the value of p2p_trend.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p2p_trend.update_time
     *
     * @param updateTime the value for p2p_trend.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}