package com.jzt.api.domain;

import java.util.Date;

public class PlatApp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_app.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_app.plat_id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer platId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_app.name
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_app.ios_address
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String iosAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_app.android_address
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String androidAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_app.ios_code_url
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String iosCodeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_app.android_code_url
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String androidCodeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_app.logo
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_app.is_ios
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer isIos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_app.is_android
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer isAndroid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_app.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_app.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_app.is_delete
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_app.id
     *
     * @return the value of plat_app.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_app.id
     *
     * @param id the value for plat_app.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_app.plat_id
     *
     * @return the value of plat_app.plat_id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getPlatId() {
        return platId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_app.plat_id
     *
     * @param platId the value for plat_app.plat_id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setPlatId(Integer platId) {
        this.platId = platId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_app.name
     *
     * @return the value of plat_app.name
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_app.name
     *
     * @param name the value for plat_app.name
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_app.ios_address
     *
     * @return the value of plat_app.ios_address
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getIosAddress() {
        return iosAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_app.ios_address
     *
     * @param iosAddress the value for plat_app.ios_address
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setIosAddress(String iosAddress) {
        this.iosAddress = iosAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_app.android_address
     *
     * @return the value of plat_app.android_address
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getAndroidAddress() {
        return androidAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_app.android_address
     *
     * @param androidAddress the value for plat_app.android_address
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setAndroidAddress(String androidAddress) {
        this.androidAddress = androidAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_app.ios_code_url
     *
     * @return the value of plat_app.ios_code_url
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getIosCodeUrl() {
        return iosCodeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_app.ios_code_url
     *
     * @param iosCodeUrl the value for plat_app.ios_code_url
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setIosCodeUrl(String iosCodeUrl) {
        this.iosCodeUrl = iosCodeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_app.android_code_url
     *
     * @return the value of plat_app.android_code_url
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getAndroidCodeUrl() {
        return androidCodeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_app.android_code_url
     *
     * @param androidCodeUrl the value for plat_app.android_code_url
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setAndroidCodeUrl(String androidCodeUrl) {
        this.androidCodeUrl = androidCodeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_app.logo
     *
     * @return the value of plat_app.logo
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_app.logo
     *
     * @param logo the value for plat_app.logo
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setLogo(String logo) {
        this.logo = logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_app.is_ios
     *
     * @return the value of plat_app.is_ios
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getIsIos() {
        return isIos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_app.is_ios
     *
     * @param isIos the value for plat_app.is_ios
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setIsIos(Integer isIos) {
        this.isIos = isIos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_app.is_android
     *
     * @return the value of plat_app.is_android
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getIsAndroid() {
        return isAndroid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_app.is_android
     *
     * @param isAndroid the value for plat_app.is_android
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setIsAndroid(Integer isAndroid) {
        this.isAndroid = isAndroid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_app.create_time
     *
     * @return the value of plat_app.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_app.create_time
     *
     * @param createTime the value for plat_app.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_app.update_time
     *
     * @return the value of plat_app.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_app.update_time
     *
     * @param updateTime the value for plat_app.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_app.is_delete
     *
     * @return the value of plat_app.is_delete
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_app.is_delete
     *
     * @param isDelete the value for plat_app.is_delete
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}