package com.jzt.api.domain;

import java.util.Date;

public class PlatContact {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_contact.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_contact.plat_id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer platId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_contact.address
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_contact.phone_400
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String phone400;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_contact.phone
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_contact.fax
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_contact.email
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_contact.weibo
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String weibo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_contact.wechat
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String wechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_contact.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_contact.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_contact.is_delete
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_contact.id
     *
     * @return the value of plat_contact.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_contact.id
     *
     * @param id the value for plat_contact.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_contact.plat_id
     *
     * @return the value of plat_contact.plat_id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getPlatId() {
        return platId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_contact.plat_id
     *
     * @param platId the value for plat_contact.plat_id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setPlatId(Integer platId) {
        this.platId = platId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_contact.address
     *
     * @return the value of plat_contact.address
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_contact.address
     *
     * @param address the value for plat_contact.address
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_contact.phone_400
     *
     * @return the value of plat_contact.phone_400
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getPhone400() {
        return phone400;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_contact.phone_400
     *
     * @param phone400 the value for plat_contact.phone_400
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setPhone400(String phone400) {
        this.phone400 = phone400;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_contact.phone
     *
     * @return the value of plat_contact.phone
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_contact.phone
     *
     * @param phone the value for plat_contact.phone
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_contact.fax
     *
     * @return the value of plat_contact.fax
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_contact.fax
     *
     * @param fax the value for plat_contact.fax
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_contact.email
     *
     * @return the value of plat_contact.email
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_contact.email
     *
     * @param email the value for plat_contact.email
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_contact.weibo
     *
     * @return the value of plat_contact.weibo
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getWeibo() {
        return weibo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_contact.weibo
     *
     * @param weibo the value for plat_contact.weibo
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setWeibo(String weibo) {
        this.weibo = weibo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_contact.wechat
     *
     * @return the value of plat_contact.wechat
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_contact.wechat
     *
     * @param wechat the value for plat_contact.wechat
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setWechat(String wechat) {
        this.wechat = wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_contact.create_time
     *
     * @return the value of plat_contact.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_contact.create_time
     *
     * @param createTime the value for plat_contact.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_contact.update_time
     *
     * @return the value of plat_contact.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_contact.update_time
     *
     * @param updateTime the value for plat_contact.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_contact.is_delete
     *
     * @return the value of plat_contact.is_delete
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_contact.is_delete
     *
     * @param isDelete the value for plat_contact.is_delete
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}