package com.jzt.api.domain;

import java.util.Date;

public class Report {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.title
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.type
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.link
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.source
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.icon
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.favorites
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer favorites;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.content
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.id
     *
     * @return the value of report.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.id
     *
     * @param id the value for report.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.title
     *
     * @return the value of report.title
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.title
     *
     * @param title the value for report.title
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.type
     *
     * @return the value of report.type
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.type
     *
     * @param type the value for report.type
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.link
     *
     * @return the value of report.link
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.link
     *
     * @param link the value for report.link
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setLink(String link) {
        this.link = link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.source
     *
     * @return the value of report.source
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.source
     *
     * @param source the value for report.source
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.icon
     *
     * @return the value of report.icon
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.icon
     *
     * @param icon the value for report.icon
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.favorites
     *
     * @return the value of report.favorites
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getFavorites() {
        return favorites;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.favorites
     *
     * @param favorites the value for report.favorites
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setFavorites(Integer favorites) {
        this.favorites = favorites;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.create_time
     *
     * @return the value of report.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.create_time
     *
     * @param createTime the value for report.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.update_time
     *
     * @return the value of report.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.update_time
     *
     * @param updateTime the value for report.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.content
     *
     * @return the value of report.content
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.content
     *
     * @param content the value for report.content
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    private int startRow;

    private int pageSize;

    public int getStartRow() {
        return startRow;
    }

    public void setStartRow(int startRow) {
        this.startRow = startRow;
    }

    public int getPageSize() {
        return pageSize;
    }

    public void setPageSize(int pageSize) {
        this.pageSize = pageSize;
    }
}