package com.jzt.api.domain;

import java.util.Date;

public class Stockholder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockholder.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockholder.company_id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockholder.type
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockholder.name
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockholder.certificate_type
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String certificateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockholder.certificate
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String certificate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockholder.occupies_compared
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String occupiesCompared;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockholder.registered_capital
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String registeredCapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockholder.des
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String des;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockholder.position
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockholder.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockholder.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stockholder.is_delete
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockholder.id
     *
     * @return the value of stockholder.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockholder.id
     *
     * @param id the value for stockholder.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockholder.company_id
     *
     * @return the value of stockholder.company_id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockholder.company_id
     *
     * @param companyId the value for stockholder.company_id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockholder.type
     *
     * @return the value of stockholder.type
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockholder.type
     *
     * @param type the value for stockholder.type
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockholder.name
     *
     * @return the value of stockholder.name
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockholder.name
     *
     * @param name the value for stockholder.name
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockholder.certificate_type
     *
     * @return the value of stockholder.certificate_type
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getCertificateType() {
        return certificateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockholder.certificate_type
     *
     * @param certificateType the value for stockholder.certificate_type
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setCertificateType(String certificateType) {
        this.certificateType = certificateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockholder.certificate
     *
     * @return the value of stockholder.certificate
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getCertificate() {
        return certificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockholder.certificate
     *
     * @param certificate the value for stockholder.certificate
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setCertificate(String certificate) {
        this.certificate = certificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockholder.occupies_compared
     *
     * @return the value of stockholder.occupies_compared
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getOccupiesCompared() {
        return occupiesCompared;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockholder.occupies_compared
     *
     * @param occupiesCompared the value for stockholder.occupies_compared
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setOccupiesCompared(String occupiesCompared) {
        this.occupiesCompared = occupiesCompared;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockholder.registered_capital
     *
     * @return the value of stockholder.registered_capital
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getRegisteredCapital() {
        return registeredCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockholder.registered_capital
     *
     * @param registeredCapital the value for stockholder.registered_capital
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setRegisteredCapital(String registeredCapital) {
        this.registeredCapital = registeredCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockholder.des
     *
     * @return the value of stockholder.des
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockholder.des
     *
     * @param des the value for stockholder.des
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setDes(String des) {
        this.des = des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockholder.position
     *
     * @return the value of stockholder.position
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockholder.position
     *
     * @param position the value for stockholder.position
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockholder.create_time
     *
     * @return the value of stockholder.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockholder.create_time
     *
     * @param createTime the value for stockholder.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockholder.update_time
     *
     * @return the value of stockholder.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockholder.update_time
     *
     * @param updateTime the value for stockholder.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stockholder.is_delete
     *
     * @return the value of stockholder.is_delete
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stockholder.is_delete
     *
     * @param isDelete the value for stockholder.is_delete
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}