package com.jzt.api.domain;

import java.util.Date;

public class UserAttentionPlatform {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_attention_platform.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_attention_platform.pId
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_attention_platform.uId
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_attention_platform.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_attention_platform.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_attention_platform.id
     *
     * @return the value of user_attention_platform.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_attention_platform.id
     *
     * @param id the value for user_attention_platform.id
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_attention_platform.pId
     *
     * @return the value of user_attention_platform.pId
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_attention_platform.pId
     *
     * @param pid the value for user_attention_platform.pId
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_attention_platform.uId
     *
     * @return the value of user_attention_platform.uId
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_attention_platform.uId
     *
     * @param uid the value for user_attention_platform.uId
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_attention_platform.create_time
     *
     * @return the value of user_attention_platform.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_attention_platform.create_time
     *
     * @param createTime the value for user_attention_platform.create_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_attention_platform.update_time
     *
     * @return the value of user_attention_platform.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_attention_platform.update_time
     *
     * @param updateTime the value for user_attention_platform.update_time
     *
     * @mbggenerated Sun Mar 12 23:14:32 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}